drop table if exists member CASCADE;
create table member
(
--    by default as identity : 값이 입력되지 않으면 자동으로 값을 넣어준다는 의미
    id bigint generated by default as identity,
    name varchar(255),
    primary key(id)
);