
--사용한 SQL문 메모 용도
DROP TABLE if EXISTS member CASCADE;
CREATE table member
(
--    bigint는 java에서 long이랑 같은 의미
--    BY DEFAULT AS IDENTITY 는 시퀀스 의미(입력값을 따로 주지 않아도 값이 증가)
    id bigint generated BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    PRIMARY KEY (id)
);